DBserver:
  db: "postgres"
  port: "5432"
  name: "taskdb"
  ssl: "disable"
  host: "localhost"
database:
  user: "vlad"
  password: "root"

AppServer:
  domain: "localhost"
  port: "8080"

CORS:
  origins: "http://localhost:8080"

Auth:
  authUrl: "http://localhost:9090/user/auth"